// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VipServices2020.EF;

namespace VipServices2020.EF.Migrations
{
    [DbContext(typeof(VipServicesContext))]
    [Migration("20200808131507_staffel")]
    partial class staffel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VipServices2020.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Customer", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("BtwNumber")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CustomerNumber");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Limousine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("FirstHourPrice")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NightLifePrice")
                        .HasColumnType("int");

                    b.Property<int>("WeddingPrice")
                        .HasColumnType("int");

                    b.Property<int>("WelnessPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Limousines");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BtwPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExclusiveBtw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FirstHourPrice")
                        .HasColumnType("int");

                    b.Property<int>("FixedPrice")
                        .HasColumnType("int");

                    b.Property<int>("NightHourCount")
                        .HasColumnType("int");

                    b.Property<decimal>("NightHourPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OvertimeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("OvertimePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SecondHourCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SecondHourPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StaffelNumberOfBookedReservations")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StaffelNumberOfBookedReservations");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArrangementType")
                        .HasColumnType("int");

                    b.Property<int?>("ArrivalLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LimousineExpectedAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("LimousineId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StartLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TotalHours")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalLocationId");

                    b.HasIndex("CustomerNumber");

                    b.HasIndex("LimousineExpectedAddressId");

                    b.HasIndex("LimousineId");

                    b.HasIndex("PriceId");

                    b.HasIndex("StartLocationId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Staffel", b =>
                {
                    b.Property<int>("NumberOfBookedReservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("NumberOfBookedReservations");

                    b.HasIndex("DiscountId");

                    b.ToTable("Staffels");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Customer", b =>
                {
                    b.HasOne("VipServices2020.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Price", b =>
                {
                    b.HasOne("VipServices2020.Domain.Models.Staffel", "Staffel")
                        .WithMany()
                        .HasForeignKey("StaffelNumberOfBookedReservations");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Reservation", b =>
                {
                    b.HasOne("VipServices2020.Domain.Models.Location", "ArrivalLocation")
                        .WithMany()
                        .HasForeignKey("ArrivalLocationId");

                    b.HasOne("VipServices2020.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerNumber");

                    b.HasOne("VipServices2020.Domain.Models.Address", "LimousineExpectedAddress")
                        .WithMany()
                        .HasForeignKey("LimousineExpectedAddressId");

                    b.HasOne("VipServices2020.Domain.Models.Limousine", "Limousine")
                        .WithMany("Reservations")
                        .HasForeignKey("LimousineId");

                    b.HasOne("VipServices2020.Domain.Models.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId");

                    b.HasOne("VipServices2020.Domain.Models.Location", "StartLocation")
                        .WithMany()
                        .HasForeignKey("StartLocationId");
                });

            modelBuilder.Entity("VipServices2020.Domain.Models.Staffel", b =>
                {
                    b.HasOne("VipServices2020.Domain.Models.Discount", null)
                        .WithMany("StaffelDiscountList")
                        .HasForeignKey("DiscountId");
                });
#pragma warning restore 612, 618
        }
    }
}
